### ISSUE TITLE
初回起動時にウィンドウが小さいとQuick Tourが見えない問題

### ISSUE THREAD

**Issue by Kurosawa0626** [omanuke/NoteApp#1]
![image](https://cloud.githubusercontent.com/assets/4182938/21145773/c9596590-c192-11e6-91ae-065b11d2905d.png)

**Comment by omanuke** [comment]
ああ、すみません古いクイックツアーが残ってました・・・(;´･ω･)
内容も古くなってるし修正します。

**Comment by omanuke** [comment]
とりあえず内容も古いのでQuickTour出さないように修正
