### ISSUE TITLE
既存Tagの編集をする際、Text ColorとBack Colorが既存の色を保持していいない。

### ISSUE THREAD

**Issue by Kurosawa0626** [omanuke/NoteApp#4]
![image](https://cloud.githubusercontent.com/assets/4182938/21306759/f2dd8752-c615-11e6-8cc6-f64a3f74dc6d.png)

変更しない限りApplyは押せないので事故りはしないと思いますが、現在の色を選択してある方が親切かと。

**Comment by omanuke** [comment]
修正します(;´･ω･)

**Comment by omanuke** [comment]
修正だん
